config/routes.rb
Rails.application.routes.draw do
  resources :publishers
  root 'landing#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/publisher.rb
class Publisher < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index
  end
end

app/controllers/publishers_controller.rb
class PublishersController < ApplicationController
  before_action :set_publisher, only: %i[ show edit update destroy ]

  # GET /publishers or /publishers.json
  def index
    @publishers = Publisher.all
  end

  # GET /publishers/1 or /publishers/1.json
  def show
  end

  # GET /publishers/new
  def new
    @publisher = Publisher.new
  end

  # GET /publishers/1/edit
  def edit
  end

  # POST /publishers or /publishers.json
  def create
    @publisher = Publisher.new(publisher_params)

    respond_to do |format|
      if @publisher.save
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully created." }
        format.json { render :show, status: :created, location: @publisher }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publishers/1 or /publishers/1.json
  def update
    respond_to do |format|
      if @publisher.update(publisher_params)
        format.html { redirect_to publisher_url(@publisher), notice: "Publisher was successfully updated." }
        format.json { render :show, status: :ok, location: @publisher }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publisher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publishers/1 or /publishers/1.json
  def destroy
    @publisher.destroy

    respond_to do |format|
      format.html { redirect_to publishers_url, notice: "Publisher was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publisher
      @publisher = Publisher.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publisher_params
      params.require(:publisher).permit(:name, :key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/publishers_helper.rb
module PublishersHelper
end

app/views/landing/index.html.erb
<h1 class="text-3xl font-bold text-center">Welcome to my Project</h1>
<p class="mb-3 text-gray-500 dark:text-gray-400 text-center">In this project I'm practicing the basics of Stimulus, Hotwire, and Tailwind CSS in rails 7!</p>

<h2 class="text-2xl mb-2 font-bold">Example# 1</h2>
<div data-controller="hello">
  <input data-hello-target="name" type="text" placeholder='type any name here'>
  <button data-action="click->hello#greet" type="button" class="outline-none text-white bg-green-700 mx-2 hover:bg-green-800 focus:ring-0 focus:ring-green-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-green-600 dark:hover:bg-green-700 dark:focus:ring-green-800">Greet</button>
  <span data-hello-target="output" class="text-gray-500"></span>
</div>

<h2 class="text-2xl my-2 font-bold">Example# 2</h2>
<div data-controller="clipboard" data-clipboard-supported-class="clipboard--supported">
  <input data-clipboard-target="source" type="text" value="7GKL08" readonly>
  <button data-action="click->clipboard#copy" type="button" class="outline-none text-white bg-gray-700 mx-2 hover:bg-gray-800 focus:ring-0 focus:ring-gray-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-600 dark:hover:bg-gray-700 dark:focus:ring-gray-800">Copy to Clipboard</button>
  <span data-clipboard-target="output" class="text-green-500"><i></i></span>
</div>

<p class="mt-3">Let's apply CRUD operations via Hotwire: </p>
<br>
<%= link_to 'Publishers', publishers_path, class: "focus:outline-none text-white bg-yellow-400 hover:bg-yellow-500 focus:ring-0 focus:ring-yellow-300 font-medium rounded-lg text-sm px-5 py-2.5 mr-2 mb-2 dark:focus:ring-yellow-900" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StimulusHotwire</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5">
      <%= yield %>
    </main>
  </body>
</html>

app/views/publishers/_form.html.erb
<%= form_with(model: publisher, class: "contents") do |form| %>
  <% if publisher.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(publisher.errors.count, "error") %> prohibited this publisher from being saved:</h2>

      <ul>
        <% publisher.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name %>
    <%= form.text_field :name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :key %>
    <%= form.text_field :key, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/publishers/_publisher.html.erb
<div id="<%= dom_id publisher %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= publisher.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Key:</strong>
    <%= publisher.key %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this publisher", publisher, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this publisher', edit_publisher_path(publisher), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/publishers/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing publisher</h1>

  <%= render "form", publisher: @publisher %>

  <%= link_to "Show this publisher", @publisher, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to publishers", publishers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/publishers/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>


  <div class="grid grid-cols-2 gap-2">
    <div>
      <div class="flex justify-between items-center">
        <h1 class="font-bold text-4xl">Publishers</h1>
        <%= link_to 'New publisher', new_publisher_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
      </div>

      <div id="publishers" class="min-w-full">
        <% @publishers.each do |publisher| %>
          <div id="<%= dom_id publisher %>">
            <p class="my-5">
              <strong class="block font-medium mb-1">Name:</strong>
              <%= publisher.name %>
            </p>

            <p class="my-5">
              <strong class="block font-medium mb-1">Key:</strong>
              <%= publisher.key %>
            </p>

            <% if action_name != "show" %>
              <%= link_to "Show this publisher", publisher, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
              <%= link_to 'Edit this publisher', edit_publisher_path(publisher), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
              <hr class="mt-6">
            <% end %>
            </div>
        <% end %>
      </div>
    </div>
    <div>
      <div class="mx-auto md:w-2/3 w-full">
        <h1 class="font-bold text-4xl">New publisher</h1>

        <%# render "form", publisher: @publisher %>

        <%= link_to 'Back to publishers', publishers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </div>
    </div>
  </div>  
</div>

app/views/publishers/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New publisher</h1>

  <%= render "form", publisher: @publisher %>

  <%= link_to 'Back to publishers', publishers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/publishers/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @publisher %>

    <%= link_to 'Edit this publisher', edit_publisher_path(@publisher), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this publisher', publisher_path(@publisher), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to publishers', publishers_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>